### ISSUE TITLE
BgenVar.minor_allele_dosage mem leak

### ISSUE THREAD

**Issue by daverblair** [jeremymcrae/bgen#1]
Hello,

I stumbled across this package when looking for a lightweight bgen parser and it definitely works nicely. However, when repeatedly calling 'BgenVar.minor_allele_dosage,' I end up with a memory leak. It looks like maybe the array constructed to return the dosage is leaving the scope of the garbage collector, but I am not totally sure. It's been awhile since I have written anything in cython (I am using version 0.29.15 with python 3.7 in case this helps). Happy to provide more details if it helps. Overall, great package and definitely quite fast. Thanks for making it public!

Dave Blair

**Comment by jeremymcrae** [comment]
Oooh, good catch! Yep, I wasn't freeing up some memory, which affected repeated calls. I've fixed this in c132193b54cf3caf42bb48efce8cbf089a307e9c, and pushed a new version (1.1.5) to pypi.

Thanks!

**Comment by daverblair** [comment]
Great! Thanks for the quick fix! I’ll let you know if there are any other issues, but so far, seems to be working great!
