### ISSUE TITLE
Build errors in building the bgen wheel on a windows 10 machine

### ISSUE THREAD

**Issue by madscientistca** [jeremymcrae/bgen#2]
When I pip install bgen the process fails when building the wheel for bgen, where it seems to fail on the zlib, where I had installed zlib using:

powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat

from:

https://github.com/horta/zlib.install

the error I get specifically in running pip install bgen from a windows powershell (running as admin) is below. Is this because the '-std=gnu11' and -fPIC options are not set correctly for this compiling under windows with vc++?  Or is this not supported on windows machines through powershell? The fatal error is the zlib.h not being found to include in the genotype.cpp file.

pip install bgen
Collecting bgen
  Using cached bgen-1.3.1.tar.gz (668 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\erics\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from bgen) (1.23.5)
Building wheels for collected packages: bgen
  Building wheel for bgen (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for bgen (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [143 lines of output]
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      debug.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      entropy_common.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      error_private.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      fse_decompress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      pool.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      threading.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      xxhash.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_common.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      fse_compress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      hist.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      huf_compress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstdmt_compress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_compress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_compress_literals.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_compress_sequences.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_double_fast.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_fast.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_lazy.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_ldm.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_opt.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      huf_decompress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_ddict.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_decompress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_decompress_block.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      cover.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      divsufsort.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      fastcover.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zdict.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zbuff_common.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zbuff_compress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zbuff_decompress.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v01.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v02.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v03.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v04.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v05.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v06.c
      cl : Command line warning D9002 : ignoring unknown option '-std=gnu11'
      cl : Command line warning D9002 : ignoring unknown option '-fPIC'
      zstd_v07.c
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-310
      creating build\lib.win32-cpython-310\bgen
      copying src\bgen\index.py -> build\lib.win32-cpython-310\bgen
      copying src\bgen\__init__.py -> build\lib.win32-cpython-310\bgen
      running build_ext
      building 'bgen.reader' extension
      creating build\temp.win32-cpython-310
      creating build\temp.win32-cpython-310\Release
      creating build\temp.win32-cpython-310\Release\src
      creating build\temp.win32-cpython-310\Release\src\bgen
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ -Isrc/zstd/lib "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc/bgen.cpp /Fobuild\temp.win32-cpython-310\Release\src/bgen.obj -std=c++11 -I/usr/include
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      bgen.cpp
      src/bgen.cpp(50): warning C4101: 'e': unreferenced local variable
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ -Isrc/zstd/lib "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc/bgen/bgen.cpp /Fobuild\temp.win32-cpython-310\Release\src/bgen/bgen.obj -std=c++11 -I/usr/include
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      bgen.cpp
      src/bgen/bgen.cpp(4222): warning C4244: 'argument': conversion from 'uint64_t' to 'long', possible loss of data
      src/bgen/bgen.cpp(6862): warning C4244: '=': conversion from 'uint64_t' to 'long', possible loss of data
      src/bgen/bgen.cpp(7314): warning C4244: '=': conversion from 'uint64_t' to 'long', possible loss of data
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isrc/ -Isrc/zstd/lib "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc/genotypes.cpp /Fobuild\temp.win32-cpython-310\Release\src/genotypes.obj -std=c++11 -I/usr/include
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      genotypes.cpp
      src/genotypes.cpp(15): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bgen
Failed to build bgen
ERROR: Could not build wheels for bgen, which is required to install pyproject.toml-based projects

**Comment by jeremymcrae** [comment]
I've pushed a new version of this package to pypi (1.4.0), which includes precompiled wheel packages for windows. pip install should work without errors now.

The windows packages include zlib, since that was the easiest way to guarantee availability. Aside from the fatal error you encountered, there ended up being a few other issues before this would compile and run all tests cleanly - some differences in compiler behavior, as well as a difference in file seeking between windows and linux. Should be good now!

**Comment by madscientistca** [comment]
Ah, awesome. Thanks a ton. I will give it another go this weekend.
