### ISSUE TITLE
Issue with Metadata in BgenReader

### ISSUE THREAD

**Issue by ejgardner-insmed** [jeremymcrae/bgen#7]
Hey Jeremy – really great library!

I think I found a bug. When reading a bgen file with Metadata, `BgenReader` can incorrectly set the flag parameters (compression / layout / has sample IDs). I was having trouble round-tripping a bgen on test where I added a brief metadata line; when I requested probability arrays to be decoded (e.g., `variant.probabilities`) I got an error that the compression was wrong. Once I removed the metadata from the bgen written by `BgenWriter` everything worked fine. Not a major issue but wanted to make you aware. Note that my 'solution' is based on very limited understanding of C and your code in `header.cpp`, so I could be mistaken, but my solution did work.

**Comment by jeremymcrae** [comment]
Thanks Eugene! I hadn't seen a file with metadata yet, so likely a bug, sorry about that! I'll fix and let you know.

**Comment by jeremymcrae** [comment]
Should be fixed now if you pip install the latest version. I had missed the crucial note "std::istream_iterator skips whitespace by default": https://en.cppreference.com/w/cpp/iterator/istream_iterator

Thanks for catching this!

**Comment by ejgardner-insmed** [comment]
Thanks Jeremy. I'll have our team implement but I'm sure it's good to go.
